### ISSUE TITLE
ssd performance reproduction

### ISSUE THREAD

**Issue by twangnh** [HiKapok/RON_Tensorflow#2]
HI! HiKapok, thanks for your work, can you share your result on ssd after modification compare to the original paper? Thank you.

**Comment by HiKapok** [comment]
@MrWanter Sorry. I won't have time to try SSD before next month. But I can tell you that the performance of my RON detector grow from 0.3 to 0.7 after these modifications, which is similar to SSD.

**Comment by twangnh** [comment]
thanks for your reply, so you mean it is clear to reach ssd performance? have you count the image expansion data augmentation trick in the original paper?

**Comment by HiKapok** [comment]
@MrWanter Yes, I use the expansion and then random cropping trick, you can find code [here](https://github.com/HiKapok/RON_Tensorflow/blob/b4c7bfe1313adf8db6ba65882f42ae09c5699c6a/preprocessing/tf_image.py#L310).
