### ISSUE TITLE
the difference between SSD_tensorflow and your code

### ISSUE THREAD

**Issue by liuqinying** [HiKapok/RON_Tensorflow#4]
Hi,
It confuses me that "Make all anchors on different layers be matched together, to avoid some suboptimal matching results". I cannot figure out what is difference bettween match bbox layer by layer and match bbox together.In fact,we mach every anchor with the gt boxx which has largest overlap with the anchor among all gt bboxes of the input image

**Comment by HiKapok** [comment]
@liuqinying I have the same confustion at first. But rethink that why we need multi-layers prediction? We want different layer will detect different scale objects. So when we match anchors, we must ensure each anchor will be assigned the suitable scale object ground truth! 

Consider one simple case when there is both a large dog and a small bottle in one image, if we match layer by layer then the bottle will be assigned to at least one anchor even at the most large scale feature map, so sub-optimal matching occured. 

Hope that helps.
